"use client";

import { useEffect, useState } from "react";
import { createOrder, createView, fetchProductById } from "../lib/api";
import LoadingGrid from "./LoadingGrid";
import RecommendationSection from "./RecommendationSection";

const demoUserId = 1;

export default function ProductDetailClient({ productId }) {
  const [product, setProduct] = useState(null);
  const [similarProducts, setSimilarProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [orderMessage, setOrderMessage] = useState("");

  useEffect(() => {
    async function loadProduct() {
      try {
        setLoading(true);
        setError("");

        const response = await fetchProductById(productId);
        setProduct(response.item);
        setSimilarProducts(response.similarProducts || []);

        await createView({
          userId: demoUserId,
          productId: Number(productId),
        });
      } catch (err) {
        setError(err.message || "Unable to load product.");
      } finally {
        setLoading(false);
      }
    }

    loadProduct();
  }, [productId]);

  async function handleOrder() {
    try {
      setOrderMessage("");
      await createOrder({
        userId: demoUserId,
        productId: Number(productId),
      });
      setOrderMessage("Order created successfully. Collaborative recommendations will improve after more purchases.");
    } catch (err) {
      setOrderMessage(err.message || "Unable to create order.");
    }
  }

  if (loading) {
    return (
      <main className="page-shell py-10">
        <LoadingGrid count={2} />
      </main>
    );
  }

  if (error || !product) {
    return (
      <main className="page-shell py-10">
        <div className="panel px-6 py-5 text-red-700">{error || "Product not found."}</div>
      </main>
    );
  }

  return (
    <main className="page-shell py-8">
      <div className="grid gap-6 lg:grid-cols-[1.05fr_0.95fr]">
        <section className="panel p-6 sm:p-8">
          <div className="rounded-[30px] bg-[linear-gradient(135deg,#183153,#345d96)] p-8 text-white">
            <p className="text-sm uppercase tracking-[0.32em] text-white/70">{product.category}</p>
            <h1 className="mt-4 text-4xl font-semibold sm:text-5xl">{product.name}</h1>
            <p className="mt-4 text-lg text-white/80">
              This detail page records views and asks the backend for similar products.
            </p>
          </div>
        </section>

        <aside className="panel p-6 sm:p-8">
          <p className="text-sm font-semibold uppercase tracking-[0.28em] text-stone-500">Product Details</p>
          <p className="mt-4 text-4xl font-bold text-slate-900">Rs. {product.price.toLocaleString("en-IN")}</p>
          <p className="mt-4 text-base leading-8 text-stone-600">
            Content-based recommendations use this product&apos;s category and price range. Collaborative recommendations come from purchase overlap across users.
          </p>

          <button className="button-primary mt-6 w-full" onClick={handleOrder} type="button">
            Create Order
          </button>

          {orderMessage ? (
            <p className="mt-4 text-sm leading-6 text-stone-600">{orderMessage}</p>
          ) : null}
        </aside>
      </div>

      <RecommendationSection
        title="Similar Products"
        subtitle="These items are generated by the content-based layer using same-category and similar-price logic."
        products={similarProducts}
      />
    </main>
  );
}
