import ProductCard from "./ProductCard";

export default function RecommendationSection({ title, subtitle, products }) {
  if (!products?.length) {
    return null;
  }

  return (
    <section className="mt-10">
      <div className="mb-5">
        <p className="text-sm font-semibold uppercase tracking-[0.28em] text-stone-500">{title}</p>
        <p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">{subtitle}</p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {products.map((product) => (
          <ProductCard
            key={`${title}-${product.id}`}
            product={product}
            caption={product.reason || "Generated by the recommendation engine."}
          />
        ))}
      </div>
    </section>
  );
}
