// Auto-generated seed data with 82 products (60 Standard + 22 Pro variants)
const users = [
  {
    "id": 1,
    "email": "alice@example.com",
    "password": "hashed_password_alice",
    "name": "Alice Johnson",
    "phone": "+91-9876543210",
    "address": "123 Main St, Mumbai",
    "preferences": "{\"notifications\":true,\"theme\":\"dark\"}",
    "totalSpent": 45000,
    "totalOrders": 8,
    "lastPurchaseAt": "2024-01-15T00:00:00.000Z"
  },
  {
    "id": 2,
    "email": "bob@example.com",
    "password": "hashed_password_bob",
    "name": "Bob Smith",
    "phone": "+91-9876543211",
    "address": "456 Oak Ave, Delhi",
    "preferences": "{\"notifi
    cations\":false,\"theme\":\"light\"}",
    "totalSpent": 89000,
    "totalOrders": 15,
    "lastPurchaseAt": "2024-01-10T00:00:00.000Z"
  },
  {
    "id": 3,
    "email": "cara@example.com",
    "password": "hashed_password_cara",
    "name": "Cara Davis",
    "phone": "+91-9876543212",
    "address": "789 Pine Rd, Bangalore",
    "preferences": "{\"notifications\":true,\"theme\":\"auto\"}",
    "totalSpent": 156000,
    "totalOrders": 22,
    "lastPurchaseAt": "2024-01-20T00:00:00.000Z"
  }
];
const products = [
  {
    "id": 1,
    "name": "Product 1",
    "description": "High quality product number 1",
    "category": "CLOTHING",
    "price": 599,
    "originalPrice": 799,
    "discount": 21,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_1.jpg?width=900",
    "images": [],
    "rating": 3.6,
    "reviewCount": 105,
    "viewCount": 510,
    "purchaseCount": 52,
    "keywords": [
      "product1",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 11,
    "trending": false,
    "featured": false
  },
  {
    "id": 2,
    "name": "Product 2",
    "description": "High quality product number 2",
    "category": "BOOKS",
    "price": 699,
    "originalPrice": 899,
    "discount": 22,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_2.jpg?width=900",
    "images": [],
    "rating": 3.7,
    "reviewCount": 110,
    "viewCount": 520,
    "purchaseCount": 54,
    "keywords": [
      "product2",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 12,
    "trending": false,
    "featured": false
  },
  {
    "id": 3,
    "name": "Product 3",
    "description": "High quality product number 3",
    "category": "HOME_APPLIANCES",
    "price": 799,
    "originalPrice": 999,
    "discount": 23,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_3.jpg?width=900",
    "images": [],
    "rating": 3.8,
    "reviewCount": 115,
    "viewCount": 530,
    "purchaseCount": 56,
    "keywords": [
      "product3",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 13,
    "trending": true,
    "featured": false
  },
  {
    "id": 4,
    "name": "Product 4",
    "description": "High quality product number 4",
    "category": "SPORTS",
    "price": 899,
    "originalPrice": 1099,
    "discount": 24,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_4.jpg?width=900",
    "images": [],
    "rating": 3.9,
    "reviewCount": 120,
    "viewCount": 540,
    "purchaseCount": 58,
    "keywords": [
      "product4",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 14,
    "trending": false,
    "featured": false
  },
  {
    "id": 5,
    "name": "Product 5",
    "description": "High quality product number 5",
    "category": "BEAUTY",
    "price": 999,
    "originalPrice": 1199,
    "discount": 25,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_5.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 125,
    "viewCount": 550,
    "purchaseCount": 60,
    "keywords": [
      "product5",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 15,
    "trending": false,
    "featured": true
  },
  {
    "id": 6,
    "name": "Product 6",
    "description": "High quality product number 6",
    "category": "TOYS",
    "price": 1099,
    "originalPrice": 1299,
    "discount": 26,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_6.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 130,
    "viewCount": 560,
    "purchaseCount": 62,
    "keywords": [
      "product6",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 16,
    "trending": true,
    "featured": false
  },
  {
    "id": 7,
    "name": "Product 7",
    "description": "High quality product number 7",
    "category": "FOOD",
    "price": 1199,
    "originalPrice": 1399,
    "discount": 27,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_7.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 135,
    "viewCount": 570,
    "purchaseCount": 64,
    "keywords": [
      "product7",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 17,
    "trending": false,
    "featured": false
  },
  {
    "id": 8,
    "name": "Product 8",
    "description": "High quality product number 8",
    "category": "JEWELRY",
    "price": 1299,
    "originalPrice": 1499,
    "discount": 28,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_8.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 140,
    "viewCount": 580,
    "purchaseCount": 66,
    "keywords": [
      "product8",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 18,
    "trending": false,
    "featured": false
  },
  {
    "id": 9,
    "name": "Product 9",
    "description": "High quality product number 9",
    "category": "OTHER",
    "price": 1399,
    "originalPrice": 1599,
    "discount": 29,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_9.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 145,
    "viewCount": 590,
    "purchaseCount": 68,
    "keywords": [
      "product9",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 19,
    "trending": true,
    "featured": false
  },
  {
    "id": 10,
    "name": "Product 10",
    "description": "High quality product number 10",
    "category": "ELECTRONICS",
    "price": 1499,
    "originalPrice": 1699,
    "discount": 30,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_10.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 150,
    "viewCount": 600,
    "purchaseCount": 70,
    "keywords": [
      "product10",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 20,
    "trending": false,
    "featured": true
  },
  {
    "id": 11,
    "name": "Product 11",
    "description": "High quality product number 11",
    "category": "CLOTHING",
    "price": 1599,
    "originalPrice": 1799,
    "discount": 31,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_11.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 155,
    "viewCount": 610,
    "purchaseCount": 72,
    "keywords": [
      "product11",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 21,
    "trending": false,
    "featured": false
  },
  {
    "id": 12,
    "name": "Product 12",
    "description": "High quality product number 12",
    "category": "BOOKS",
    "price": 1699,
    "originalPrice": 1899,
    "discount": 32,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_12.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 160,
    "viewCount": 620,
    "purchaseCount": 74,
    "keywords": [
      "product12",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 22,
    "trending": true,
    "featured": false
  },
  {
    "id": 13,
    "name": "Product 13",
    "description": "High quality product number 13",
    "category": "HOME_APPLIANCES",
    "price": 1799,
    "originalPrice": 1999,
    "discount": 33,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_13.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 165,
    "viewCount": 630,
    "purchaseCount": 76,
    "keywords": [
      "product13",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 23,
    "trending": false,
    "featured": false
  },
  {
    "id": 14,
    "name": "Product 14",
    "description": "High quality product number 14",
    "category": "SPORTS",
    "price": 1899,
    "originalPrice": 2099,
    "discount": 34,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_14.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 170,
    "viewCount": 640,
    "purchaseCount": 78,
    "keywords": [
      "product14",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 24,
    "trending": false,
    "featured": false
  },
  {
    "id": 15,
    "name": "Product 15",
    "description": "High quality product number 15",
    "category": "BEAUTY",
    "price": 1999,
    "originalPrice": 2199,
    "discount": 20,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_15.jpg?width=900",
    "images": [],
    "rating": 3.5,
    "reviewCount": 175,
    "viewCount": 650,
    "purchaseCount": 80,
    "keywords": [
      "product15",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 25,
    "trending": true,
    "featured": true
  },
  {
    "id": 16,
    "name": "Product 16",
    "description": "High quality product number 16",
    "category": "TOYS",
    "price": 2099,
    "originalPrice": 2299,
    "discount": 21,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_16.jpg?width=900",
    "images": [],
    "rating": 3.6,
    "reviewCount": 180,
    "viewCount": 660,
    "purchaseCount": 82,
    "keywords": [
      "product16",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 26,
    "trending": false,
    "featured": false
  },
  {
    "id": 17,
    "name": "Product 17",
    "description": "High quality product number 17",
    "category": "FOOD",
    "price": 2199,
    "originalPrice": 2399,
    "discount": 22,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_17.jpg?width=900",
    "images": [],
    "rating": 3.7,
    "reviewCount": 185,
    "viewCount": 670,
    "purchaseCount": 84,
    "keywords": [
      "product17",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 27,
    "trending": false,
    "featured": false
  },
  {
    "id": 18,
    "name": "Product 18",
    "description": "High quality product number 18",
    "category": "JEWELRY",
    "price": 2299,
    "originalPrice": 2499,
    "discount": 23,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_18.jpg?width=900",
    "images": [],
    "rating": 3.8,
    "reviewCount": 190,
    "viewCount": 680,
    "purchaseCount": 86,
    "keywords": [
      "product18",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 28,
    "trending": true,
    "featured": false
  },
  {
    "id": 19,
    "name": "Product 19",
    "description": "High quality product number 19",
    "category": "OTHER",
    "price": 2399,
    "originalPrice": 2599,
    "discount": 24,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_19.jpg?width=900",
    "images": [],
    "rating": 3.9,
    "reviewCount": 195,
    "viewCount": 690,
    "purchaseCount": 88,
    "keywords": [
      "product19",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 29,
    "trending": false,
    "featured": false
  },
  {
    "id": 20,
    "name": "Product 20",
    "description": "High quality product number 20",
    "category": "ELECTRONICS",
    "price": 2499,
    "originalPrice": 2699,
    "discount": 25,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_20.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 200,
    "viewCount": 700,
    "purchaseCount": 90,
    "keywords": [
      "product20",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 30,
    "trending": false,
    "featured": true
  },
  {
    "id": 21,
    "name": "Product 21",
    "description": "High quality product number 21",
    "category": "CLOTHING",
    "price": 2599,
    "originalPrice": 2799,
    "discount": 26,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_21.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 205,
    "viewCount": 710,
    "purchaseCount": 92,
    "keywords": [
      "product21",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 31,
    "trending": true,
    "featured": false
  },
  {
    "id": 22,
    "name": "Product 22",
    "description": "High quality product number 22",
    "category": "BOOKS",
    "price": 2699,
    "originalPrice": 2899,
    "discount": 27,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_22.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 210,
    "viewCount": 720,
    "purchaseCount": 94,
    "keywords": [
      "product22",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 32,
    "trending": false,
    "featured": false
  },
  {
    "id": 23,
    "name": "Product 23",
    "description": "High quality product number 23",
    "category": "HOME_APPLIANCES",
    "price": 2799,
    "originalPrice": 2999,
    "discount": 28,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_23.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 215,
    "viewCount": 730,
    "purchaseCount": 96,
    "keywords": [
      "product23",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 33,
    "trending": false,
    "featured": false
  },
  {
    "id": 24,
    "name": "Product 24",
    "description": "High quality product number 24",
    "category": "SPORTS",
    "price": 2899,
    "originalPrice": 3099,
    "discount": 29,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_24.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 220,
    "viewCount": 740,
    "purchaseCount": 98,
    "keywords": [
      "product24",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 34,
    "trending": true,
    "featured": false
  },
  {
    "id": 25,
    "name": "Product 25",
    "description": "High quality product number 25",
    "category": "BEAUTY",
    "price": 2999,
    "originalPrice": 3199,
    "discount": 30,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_25.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 225,
    "viewCount": 750,
    "purchaseCount": 100,
    "keywords": [
      "product25",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 35,
    "trending": false,
    "featured": true
  },
  {
    "id": 26,
    "name": "Product 26",
    "description": "High quality product number 26",
    "category": "TOYS",
    "price": 3099,
    "originalPrice": 3299,
    "discount": 31,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_26.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 230,
    "viewCount": 760,
    "purchaseCount": 102,
    "keywords": [
      "product26",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 36,
    "trending": false,
    "featured": false
  },
  {
    "id": 27,
    "name": "Product 27",
    "description": "High quality product number 27",
    "category": "FOOD",
    "price": 3199,
    "originalPrice": 3399,
    "discount": 32,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_27.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 235,
    "viewCount": 770,
    "purchaseCount": 104,
    "keywords": [
      "product27",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 37,
    "trending": true,
    "featured": false
  },
  {
    "id": 28,
    "name": "Product 28",
    "description": "High quality product number 28",
    "category": "JEWELRY",
    "price": 3299,
    "originalPrice": 3499,
    "discount": 33,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_28.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 240,
    "viewCount": 780,
    "purchaseCount": 106,
    "keywords": [
      "product28",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 38,
    "trending": false,
    "featured": false
  },
  {
    "id": 29,
    "name": "Product 29",
    "description": "High quality product number 29",
    "category": "OTHER",
    "price": 3399,
    "originalPrice": 3599,
    "discount": 34,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_29.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 245,
    "viewCount": 790,
    "purchaseCount": 108,
    "keywords": [
      "product29",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 39,
    "trending": false,
    "featured": false
  },
  {
    "id": 30,
    "name": "Product 30",
    "description": "High quality product number 30",
    "category": "ELECTRONICS",
    "price": 3499,
    "originalPrice": 3699,
    "discount": 20,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_30.jpg?width=900",
    "images": [],
    "rating": 3.5,
    "reviewCount": 250,
    "viewCount": 800,
    "purchaseCount": 110,
    "keywords": [
      "product30",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 40,
    "trending": true,
    "featured": true
  },
  {
    "id": 31,
    "name": "Product 31",
    "description": "High quality product number 31",
    "category": "CLOTHING",
    "price": 3599,
    "originalPrice": 3799,
    "discount": 21,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_31.jpg?width=900",
    "images": [],
    "rating": 3.6,
    "reviewCount": 255,
    "viewCount": 810,
    "purchaseCount": 112,
    "keywords": [
      "product31",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 41,
    "trending": false,
    "featured": false
  },
  {
    "id": 32,
    "name": "Product 32",
    "description": "High quality product number 32",
    "category": "BOOKS",
    "price": 3699,
    "originalPrice": 3899,
    "discount": 22,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_32.jpg?width=900",
    "images": [],
    "rating": 3.7,
    "reviewCount": 260,
    "viewCount": 820,
    "purchaseCount": 114,
    "keywords": [
      "product32",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 42,
    "trending": false,
    "featured": false
  },
  {
    "id": 33,
    "name": "Product 33",
    "description": "High quality product number 33",
    "category": "HOME_APPLIANCES",
    "price": 3799,
    "originalPrice": 3999,
    "discount": 23,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_33.jpg?width=900",
    "images": [],
    "rating": 3.8,
    "reviewCount": 265,
    "viewCount": 830,
    "purchaseCount": 116,
    "keywords": [
      "product33",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 43,
    "trending": true,
    "featured": false
  },
  {
    "id": 34,
    "name": "Product 34",
    "description": "High quality product number 34",
    "category": "SPORTS",
    "price": 3899,
    "originalPrice": 4099,
    "discount": 24,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_34.jpg?width=900",
    "images": [],
    "rating": 3.9,
    "reviewCount": 270,
    "viewCount": 840,
    "purchaseCount": 118,
    "keywords": [
      "product34",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 44,
    "trending": false,
    "featured": false
  },
  {
    "id": 35,
    "name": "Product 35",
    "description": "High quality product number 35",
    "category": "BEAUTY",
    "price": 3999,
    "originalPrice": 4199,
    "discount": 25,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_35.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 275,
    "viewCount": 850,
    "purchaseCount": 120,
    "keywords": [
      "product35",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 45,
    "trending": false,
    "featured": true
  },
  {
    "id": 36,
    "name": "Product 36",
    "description": "High quality product number 36",
    "category": "TOYS",
    "price": 4099,
    "originalPrice": 4299,
    "discount": 26,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_36.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 280,
    "viewCount": 860,
    "purchaseCount": 122,
    "keywords": [
      "product36",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 46,
    "trending": true,
    "featured": false
  },
  {
    "id": 37,
    "name": "Product 37",
    "description": "High quality product number 37",
    "category": "FOOD",
    "price": 4199,
    "originalPrice": 4399,
    "discount": 27,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_37.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 285,
    "viewCount": 870,
    "purchaseCount": 124,
    "keywords": [
      "product37",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 47,
    "trending": false,
    "featured": false
  },
  {
    "id": 38,
    "name": "Product 38",
    "description": "High quality product number 38",
    "category": "JEWELRY",
    "price": 4299,
    "originalPrice": 4499,
    "discount": 28,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_38.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 290,
    "viewCount": 880,
    "purchaseCount": 126,
    "keywords": [
      "product38",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 48,
    "trending": false,
    "featured": false
  },
  {
    "id": 39,
    "name": "Product 39",
    "description": "High quality product number 39",
    "category": "OTHER",
    "price": 4399,
    "originalPrice": 4599,
    "discount": 29,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_39.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 295,
    "viewCount": 890,
    "purchaseCount": 128,
    "keywords": [
      "product39",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 49,
    "trending": true,
    "featured": false
  },
  {
    "id": 40,
    "name": "Product 40",
    "description": "High quality product number 40",
    "category": "ELECTRONICS",
    "price": 4499,
    "originalPrice": 4699,
    "discount": 30,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_40.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 300,
    "viewCount": 900,
    "purchaseCount": 130,
    "keywords": [
      "product40",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 50,
    "trending": false,
    "featured": true
  },
  {
    "id": 41,
    "name": "Product 41",
    "description": "High quality product number 41",
    "category": "CLOTHING",
    "price": 4599,
    "originalPrice": 4799,
    "discount": 31,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_41.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 305,
    "viewCount": 910,
    "purchaseCount": 132,
    "keywords": [
      "product41",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 51,
    "trending": false,
    "featured": false
  },
  {
    "id": 42,
    "name": "Product 42",
    "description": "High quality product number 42",
    "category": "BOOKS",
    "price": 4699,
    "originalPrice": 4899,
    "discount": 32,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_42.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 310,
    "viewCount": 920,
    "purchaseCount": 134,
    "keywords": [
      "product42",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 52,
    "trending": true,
    "featured": false
  },
  {
    "id": 43,
    "name": "Product 43",
    "description": "High quality product number 43",
    "category": "HOME_APPLIANCES",
    "price": 4799,
    "originalPrice": 4999,
    "discount": 33,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_43.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 315,
    "viewCount": 930,
    "purchaseCount": 136,
    "keywords": [
      "product43",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 53,
    "trending": false,
    "featured": false
  },
  {
    "id": 44,
    "name": "Product 44",
    "description": "High quality product number 44",
    "category": "SPORTS",
    "price": 4899,
    "originalPrice": 5099,
    "discount": 34,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_44.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 320,
    "viewCount": 940,
    "purchaseCount": 138,
    "keywords": [
      "product44",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 54,
    "trending": false,
    "featured": false
  },
  {
    "id": 45,
    "name": "Product 45",
    "description": "High quality product number 45",
    "category": "BEAUTY",
    "price": 4999,
    "originalPrice": 5199,
    "discount": 20,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_45.jpg?width=900",
    "images": [],
    "rating": 3.5,
    "reviewCount": 325,
    "viewCount": 950,
    "purchaseCount": 140,
    "keywords": [
      "product45",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 55,
    "trending": true,
    "featured": true
  },
  {
    "id": 46,
    "name": "Product 46",
    "description": "High quality product number 46",
    "category": "TOYS",
    "price": 5099,
    "originalPrice": 5299,
    "discount": 21,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_46.jpg?width=900",
    "images": [],
    "rating": 3.6,
    "reviewCount": 330,
    "viewCount": 960,
    "purchaseCount": 142,
    "keywords": [
      "product46",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 56,
    "trending": false,
    "featured": false
  },
  {
    "id": 47,
    "name": "Product 47",
    "description": "High quality product number 47",
    "category": "FOOD",
    "price": 5199,
    "originalPrice": 5399,
    "discount": 22,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_47.jpg?width=900",
    "images": [],
    "rating": 3.7,
    "reviewCount": 335,
    "viewCount": 970,
    "purchaseCount": 144,
    "keywords": [
      "product47",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 57,
    "trending": false,
    "featured": false
  },
  {
    "id": 48,
    "name": "Product 48",
    "description": "High quality product number 48",
    "category": "JEWELRY",
    "price": 5299,
    "originalPrice": 5499,
    "discount": 23,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_48.jpg?width=900",
    "images": [],
    "rating": 3.8,
    "reviewCount": 340,
    "viewCount": 980,
    "purchaseCount": 146,
    "keywords": [
      "product48",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 58,
    "trending": true,
    "featured": false
  },
  {
    "id": 49,
    "name": "Product 49",
    "description": "High quality product number 49",
    "category": "OTHER",
    "price": 5399,
    "originalPrice": 5599,
    "discount": 24,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_49.jpg?width=900",
    "images": [],
    "rating": 3.9,
    "reviewCount": 345,
    "viewCount": 990,
    "purchaseCount": 148,
    "keywords": [
      "product49",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 59,
    "trending": false,
    "featured": false
  },
  {
    "id": 50,
    "name": "Product 50",
    "description": "High quality product number 50",
    "category": "ELECTRONICS",
    "price": 5499,
    "originalPrice": 5699,
    "discount": 25,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_50.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 350,
    "viewCount": 1000,
    "purchaseCount": 150,
    "keywords": [
      "product50",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 10,
    "trending": false,
    "featured": true
  },
  {
    "id": 51,
    "name": "Product 51",
    "description": "High quality product number 51",
    "category": "CLOTHING",
    "price": 5599,
    "originalPrice": 5799,
    "discount": 26,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_51.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 355,
    "viewCount": 1010,
    "purchaseCount": 152,
    "keywords": [
      "product51",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 11,
    "trending": true,
    "featured": false
  },
  {
    "id": 52,
    "name": "Product 52",
    "description": "High quality product number 52",
    "category": "BOOKS",
    "price": 5699,
    "originalPrice": 5899,
    "discount": 27,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_52.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 360,
    "viewCount": 1020,
    "purchaseCount": 154,
    "keywords": [
      "product52",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 12,
    "trending": false,
    "featured": false
  },
  {
    "id": 53,
    "name": "Product 53",
    "description": "High quality product number 53",
    "category": "HOME_APPLIANCES",
    "price": 5799,
    "originalPrice": 5999,
    "discount": 28,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_53.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 365,
    "viewCount": 1030,
    "purchaseCount": 156,
    "keywords": [
      "product53",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 13,
    "trending": false,
    "featured": false
  },
  {
    "id": 54,
    "name": "Product 54",
    "description": "High quality product number 54",
    "category": "SPORTS",
    "price": 5899,
    "originalPrice": 6099,
    "discount": 29,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_54.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 370,
    "viewCount": 1040,
    "purchaseCount": 158,
    "keywords": [
      "product54",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 14,
    "trending": true,
    "featured": false
  },
  {
    "id": 55,
    "name": "Product 55",
    "description": "High quality product number 55",
    "category": "BEAUTY",
    "price": 5999,
    "originalPrice": 6199,
    "discount": 30,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_55.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 375,
    "viewCount": 1050,
    "purchaseCount": 160,
    "keywords": [
      "product55",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 15,
    "trending": false,
    "featured": true
  },
  {
    "id": 56,
    "name": "Product 56",
    "description": "High quality product number 56",
    "category": "TOYS",
    "price": 6099,
    "originalPrice": 6299,
    "discount": 31,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_56.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 380,
    "viewCount": 1060,
    "purchaseCount": 162,
    "keywords": [
      "product56",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 16,
    "trending": false,
    "featured": false
  },
  {
    "id": 57,
    "name": "Product 57",
    "description": "High quality product number 57",
    "category": "FOOD",
    "price": 6199,
    "originalPrice": 6399,
    "discount": 32,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_57.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 385,
    "viewCount": 1070,
    "purchaseCount": 164,
    "keywords": [
      "product57",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 17,
    "trending": true,
    "featured": false
  },
  {
    "id": 58,
    "name": "Product 58",
    "description": "High quality product number 58",
    "category": "JEWELRY",
    "price": 6299,
    "originalPrice": 6499,
    "discount": 33,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_58.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 390,
    "viewCount": 1080,
    "purchaseCount": 166,
    "keywords": [
      "product58",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 18,
    "trending": false,
    "featured": false
  },
  {
    "id": 59,
    "name": "Product 59",
    "description": "High quality product number 59",
    "category": "OTHER",
    "price": 6399,
    "originalPrice": 6599,
    "discount": 34,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_59.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 395,
    "viewCount": 1090,
    "purchaseCount": 168,
    "keywords": [
      "product59",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 19,
    "trending": false,
    "featured": false
  },
  {
    "id": 60,
    "name": "Product 60",
    "description": "High quality product number 60",
    "category": "ELECTRONICS",
    "price": 6499,
    "originalPrice": 6699,
    "discount": 20,
    "variant": "Standard",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Product_60.jpg?width=900",
    "images": [],
    "rating": 3.5,
    "reviewCount": 400,
    "viewCount": 1100,
    "purchaseCount": 170,
    "keywords": [
      "product60",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 20,
    "trending": true,
    "featured": true
  },
  {
    "id": 61,
    "name": "Product 61 Pro",
    "description": "Premium variant of product 1",
    "category": "CLOTHING",
    "price": 10499,
    "originalPrice": 14499,
    "discount": 26,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_61.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 210,
    "viewCount": 1020,
    "purchaseCount": 105,
    "keywords": [
      "premium61",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 6,
    "trending": false,
    "featured": false
  },
  {
    "id": 62,
    "name": "Product 62 Professional",
    "description": "Premium variant of product 2",
    "category": "BOOKS",
    "price": 10999,
    "originalPrice": 14999,
    "discount": 27,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_62.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 220,
    "viewCount": 1040,
    "purchaseCount": 110,
    "keywords": [
      "premium62",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 7,
    "trending": true,
    "featured": false
  },
  {
    "id": 63,
    "name": "Product 63 Premium",
    "description": "Premium variant of product 3",
    "category": "HOME_APPLIANCES",
    "price": 11499,
    "originalPrice": 15499,
    "discount": 28,
    "variant": "Premium",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_63.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 230,
    "viewCount": 1060,
    "purchaseCount": 115,
    "keywords": [
      "premium63",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 8,
    "trending": false,
    "featured": true
  },
  {
    "id": 64,
    "name": "Product 64 Ultra",
    "description": "Premium variant of product 4",
    "category": "SPORTS",
    "price": 11999,
    "originalPrice": 15999,
    "discount": 29,
    "variant": "Ultra",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_64.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 240,
    "viewCount": 1080,
    "purchaseCount": 120,
    "keywords": [
      "premium64",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 9,
    "trending": true,
    "featured": false
  },
  {
    "id": 65,
    "name": "Product 65 Pro",
    "description": "Premium variant of product 5",
    "category": "BEAUTY",
    "price": 12499,
    "originalPrice": 16499,
    "discount": 30,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_65.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 250,
    "viewCount": 1100,
    "purchaseCount": 125,
    "keywords": [
      "premium65",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 10,
    "trending": false,
    "featured": false
  },
  {
    "id": 66,
    "name": "Product 66 Professional",
    "description": "Premium variant of product 6",
    "category": "TOYS",
    "price": 12999,
    "originalPrice": 16999,
    "discount": 31,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_66.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 260,
    "viewCount": 1120,
    "purchaseCount": 130,
    "keywords": [
      "premium66",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 11,
    "trending": true,
    "featured": true
  },
  {
    "id": 67,
    "name": "Product 67 Premium",
    "description": "Premium variant of product 7",
    "category": "FOOD",
    "price": 13499,
    "originalPrice": 17499,
    "discount": 32,
    "variant": "Premium",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_67.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 270,
    "viewCount": 1140,
    "purchaseCount": 135,
    "keywords": [
      "premium67",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 12,
    "trending": false,
    "featured": false
  },
  {
    "id": 68,
    "name": "Product 68 Ultra",
    "description": "Premium variant of product 8",
    "category": "JEWELRY",
    "price": 13999,
    "originalPrice": 17999,
    "discount": 33,
    "variant": "Ultra",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_68.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 280,
    "viewCount": 1160,
    "purchaseCount": 140,
    "keywords": [
      "premium68",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 13,
    "trending": true,
    "featured": false
  },
  {
    "id": 69,
    "name": "Product 69 Pro",
    "description": "Premium variant of product 9",
    "category": "OTHER",
    "price": 14499,
    "originalPrice": 18499,
    "discount": 34,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_69.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 290,
    "viewCount": 1180,
    "purchaseCount": 145,
    "keywords": [
      "premium69",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 14,
    "trending": false,
    "featured": true
  },
  {
    "id": 70,
    "name": "Product 70 Professional",
    "description": "Premium variant of product 10",
    "category": "ELECTRONICS",
    "price": 14999,
    "originalPrice": 18999,
    "discount": 25,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_70.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 300,
    "viewCount": 1200,
    "purchaseCount": 150,
    "keywords": [
      "premium70",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 15,
    "trending": true,
    "featured": false
  },
  {
    "id": 71,
    "name": "Product 71 Premium",
    "description": "Premium variant of product 11",
    "category": "CLOTHING",
    "price": 15499,
    "originalPrice": 19499,
    "discount": 26,
    "variant": "Premium",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_71.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 310,
    "viewCount": 1220,
    "purchaseCount": 155,
    "keywords": [
      "premium71",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 16,
    "trending": false,
    "featured": false
  },
  {
    "id": 72,
    "name": "Product 72 Ultra",
    "description": "Premium variant of product 12",
    "category": "BOOKS",
    "price": 15999,
    "originalPrice": 19999,
    "discount": 27,
    "variant": "Ultra",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_72.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 320,
    "viewCount": 1240,
    "purchaseCount": 160,
    "keywords": [
      "premium72",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 17,
    "trending": true,
    "featured": true
  },
  {
    "id": 73,
    "name": "Product 73 Pro",
    "description": "Premium variant of product 13",
    "category": "HOME_APPLIANCES",
    "price": 16499,
    "originalPrice": 20499,
    "discount": 28,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_73.jpg?width=900",
    "images": [],
    "rating": 4.3,
    "reviewCount": 330,
    "viewCount": 1260,
    "purchaseCount": 165,
    "keywords": [
      "premium73",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 18,
    "trending": false,
    "featured": false
  },
  {
    "id": 74,
    "name": "Product 74 Professional",
    "description": "Premium variant of product 14",
    "category": "SPORTS",
    "price": 16999,
    "originalPrice": 20999,
    "discount": 29,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_74.jpg?width=900",
    "images": [],
    "rating": 4.4,
    "reviewCount": 340,
    "viewCount": 1280,
    "purchaseCount": 170,
    "keywords": [
      "premium74",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 19,
    "trending": true,
    "featured": false
  },
  {
    "id": 75,
    "name": "Product 75 Premium",
    "description": "Premium variant of product 15",
    "category": "BEAUTY",
    "price": 17499,
    "originalPrice": 21499,
    "discount": 30,
    "variant": "Premium",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_75.jpg?width=900",
    "images": [],
    "rating": 4.5,
    "reviewCount": 350,
    "viewCount": 1300,
    "purchaseCount": 175,
    "keywords": [
      "premium75",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 20,
    "trending": false,
    "featured": true
  },
  {
    "id": 76,
    "name": "Product 76 Ultra",
    "description": "Premium variant of product 16",
    "category": "TOYS",
    "price": 17999,
    "originalPrice": 21999,
    "discount": 31,
    "variant": "Ultra",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_76.jpg?width=900",
    "images": [],
    "rating": 4.6,
    "reviewCount": 360,
    "viewCount": 1320,
    "purchaseCount": 180,
    "keywords": [
      "premium76",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 21,
    "trending": true,
    "featured": false
  },
  {
    "id": 77,
    "name": "Product 77 Pro",
    "description": "Premium variant of product 17",
    "category": "FOOD",
    "price": 18499,
    "originalPrice": 22499,
    "discount": 32,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_77.jpg?width=900",
    "images": [],
    "rating": 4.7,
    "reviewCount": 370,
    "viewCount": 1340,
    "purchaseCount": 185,
    "keywords": [
      "premium77",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 22,
    "trending": false,
    "featured": false
  },
  {
    "id": 78,
    "name": "Product 78 Professional",
    "description": "Premium variant of product 18",
    "category": "JEWELRY",
    "price": 18999,
    "originalPrice": 22999,
    "discount": 33,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_78.jpg?width=900",
    "images": [],
    "rating": 4.8,
    "reviewCount": 380,
    "viewCount": 1360,
    "purchaseCount": 190,
    "keywords": [
      "premium78",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 23,
    "trending": true,
    "featured": true
  },
  {
    "id": 79,
    "name": "Product 79 Premium",
    "description": "Premium variant of product 19",
    "category": "OTHER",
    "price": 19499,
    "originalPrice": 23499,
    "discount": 34,
    "variant": "Premium",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_79.jpg?width=900",
    "images": [],
    "rating": 4.9,
    "reviewCount": 390,
    "viewCount": 1380,
    "purchaseCount": 195,
    "keywords": [
      "premium79",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 24,
    "trending": false,
    "featured": false
  },
  {
    "id": 80,
    "name": "Product 80 Ultra",
    "description": "Premium variant of product 20",
    "category": "ELECTRONICS",
    "price": 19999,
    "originalPrice": 23999,
    "discount": 25,
    "variant": "Ultra",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_80.jpg?width=900",
    "images": [],
    "rating": 4,
    "reviewCount": 400,
    "viewCount": 1400,
    "purchaseCount": 200,
    "keywords": [
      "premium80",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 5,
    "trending": true,
    "featured": false
  },
  {
    "id": 81,
    "name": "Product 81 Pro",
    "description": "Premium variant of product 21",
    "category": "CLOTHING",
    "price": 20499,
    "originalPrice": 24499,
    "discount": 26,
    "variant": "Pro",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_81.jpg?width=900",
    "images": [],
    "rating": 4.1,
    "reviewCount": 410,
    "viewCount": 1420,
    "purchaseCount": 205,
    "keywords": [
      "premium81",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 6,
    "trending": false,
    "featured": true
  },
  {
    "id": 82,
    "name": "Product 82 Professional",
    "description": "Premium variant of product 22",
    "category": "BOOKS",
    "price": 20999,
    "originalPrice": 24999,
    "discount": 27,
    "variant": "Professional",
    "imageUrl": "https://commons.wikimedia.org/wiki/Special:FilePath/Premium_Product_82.jpg?width=900",
    "images": [],
    "rating": 4.2,
    "reviewCount": 420,
    "viewCount": 1440,
    "purchaseCount": 210,
    "keywords": [
      "premium82",
      "quality"
    ],
    "inStock": true,
    "stockQuantity": 7,
    "trending": true,
    "featured": false
  }
];
const orders = [
  {
    "id": 1,
    "userId": 1,
    "productId": 1
  },
  {
    "id": 2,
    "userId": 1,
    "productId": 3
  },
  {
    "id": 3,
    "userId": 2,
    "productId": 1
  },
  {
    "id": 4,
    "userId": 2,
    "productId": 2
  },
  {
    "id": 5,
    "userId": 2,
    "productId": 5
  },
  {
    "id": 6,
    "userId": 3,
    "productId": 7
  }
];
const viewHistory = [
  {
    "id": 1,
    "userId": 1,
    "productId": 1
  },
  {
    "id": 2,
    "userId": 1,
    "productId": 2
  },
  {
    "id": 3,
    "userId": 1,
    "productId": 3
  },
  {
    "id": 4,
    "userId": 2,
    "productId": 4
  },
  {
    "id": 5,
    "userId": 2,
    "productId": 5
  },
  {
    "id": 6,
    "userId": 3,
    "productId": 7
  },
  {
    "id": 7,
    "userId": 3,
    "productId": 8
  }
];

module.exports = {
  users,
  products,
  orders,
  viewHistory,
};
